version: '{build}'

environment:
  matrix:
  - CHOCO_PERL_PACKAGE: StrawberryPerl
    CHOCO_PERL_PATH: C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
# commented as insanely slower than SP
#  - CHOCO_PERL_PACKAGE: activeperl
#    CHOCO_PERL_PATH: C:\Perl64\bin;C:\Perl64\site\bin;%PATH%

install:
  # running under CI
  - set CI_TESTING=1
  - cinst %CHOCO_PERL_PACKAGE%
  - path %CHOCO_PERL_PATH%
  - mkdir %APPVEYOR_BUILD_FOLDER%\tmp
  - set TMPDIR=%APPVEYOR_BUILD_FOLDER%\tmp
  - perl -V
  - 'echo installed at: & time /t'

build_script:
  - winnt\microsft\vpp40\mk.cmd

test_script:
  - dir
