#!/bin/sh

# 01.09.2005 Volker Quetschke
# Tests if dmake can work with makefiles with DOS lineendings.
# (issue 52238)

: ${DMAKEPROG:=dmake}
file1="mymakefile.mk"
file2="mymakefile_dos.mk"
tmpfiles="$file1 $file2"
STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
$CLEANUP # Zap remnants of any failed run
mkdir "$WORKDIR"; cd "$WORKDIR"

trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15

# Remember to quote variables in generated makefiles( $ -> \$ ).
cat > $file1 <<EOT
# Testing continuation char in recipes
SHELL*:=/bin/sh
SHELLFLAGS*:=-ce

.NOTABS	  !:= yes

all:

	echo aaa

EOT

#more compatible version of: unix2dos $file1
: ${AWK:=awk}
#$AWK 'sub("$", "\r")' $file1 > $file2
$AWK '{print $0"\r"}' $file1 > $file2

../${DMAKEPROG} -r -f $file2
result=$?

test $result -eq 0 && echo "Success - Cleaning up" && $CLEANUP
test $result -ne 0 && echo "Failure!"
exit $result
