#!/bin/sh

# 26.02.2006 Volker Quetschke
# Test if dmake complains about circular dependencies when using
# infered .INCLUDE targets
# (issue 62118)

: ${DMAKEPROG:=dmake}
file1="mfile1.mk"
file2="mytarget.dpcc"
tmpfiles="$file1 $file2"
STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
$CLEANUP # Zap remnants of any failed run
mkdir "$WORKDIR"; cd "$WORKDIR"

trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15

# Remember to quote variables in generated makefiles( $ -> \$ ).
cat > $file1 <<EOT
# Verify that makefile generation is finished when using it
SHELL*:=/bin/sh
SHELLFLAGS*:=-ce

%.dpcc :
	@echo making: \$@
	@+echo AA=123 > \$@

.INCLUDE : mytarget.dpcc

ALL : mytarget.dpcc

EOT

output=`eval ../${DMAKEPROG} -r -f $file1`
result=$?

test $result -eq 0 && echo "Success - Cleaning up" && $CLEANUP
test $result -ne 0 && echo "Failure! Invalid circular dependency detected."
exit $result
