#!/bin/sh

# 13.10.2007 Volker Quetschke
# Check that SHELLCMDQUOTE adds the characters to the command.
# issue 81252

: ${DMAKEPROG:=dmake}
file1="mfile1.mk"
tmpfiles="$file1"
CLEANUP="rm -rf $tmpfiles"

trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15

# Remove files from prior failed run
$CLEANUP

# Remember to quote variables in generated makefiles ( $ -> \$ ).
cat > $file1 <<EOT
SHELL!:=printf
SHELLFLAGS!:=

SHELLCMDQUOTE=X

all :
	@+testtest

EOT

output=`eval ${DMAKEPROG} -rf $file1`
result=$?

if test "$result" = "0" && test "$output" = "XtesttestX" ; then
  # OK
  dummy=1
else
  echo "Wrong result: ${output}"
  result=1
fi

test $result -eq 0 && echo "Success - Cleaning up" && $CLEANUP
test $result -ne 0 && echo "Failure!"
exit $result
