#!/bin/sh

# 16.06.2006 Volker Quetschke
# A comparison with the empty string crashes dmake - equality test with empty
# string must work too.
# (issue 65281)

: ${DMAKEPROG:=dmake}
file1="mfile1.mk"
tmpfiles="$file1"
STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
$CLEANUP # Zap remnants of any failed run
mkdir "$WORKDIR"; cd "$WORKDIR"

trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15

# Remember to quote variables in generated makefiles( $ -> \$ ).
cat > $file1 <<EOT
SHELL*:=/bin/sh
SHELLFLAGS*:=-ce

RHS=

all:
.IF \$(LHS) == \$(RHS)
	+@echo "true"
.ELSE
	+@echo "false"
.ENDIF

EOT

output=`eval ../${DMAKEPROG} -r -f $file1`
result=$?

if test "$output" != "true"; then
  result=1
fi

test $result -eq 0 && echo "Success - Cleaning up" && $CLEANUP
test $result -ne 0 && echo "Failure!"
exit $result
