#!/bin/sh

# 22.06.2006 Volker Quetschke
# Conditional expressions failed before with line continuations.
# (issue 66659)

: ${DMAKEPROG:=dmake}
file1="mfile1.mk"
tmpfiles="$file1"
CLEANUP="rm -rf $tmpfiles"

trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15

# Remove files from prior failed run
$CLEANUP

# Remember to quote variables in generated makefiles ( $ -> \$ ).
# Also quote line continuations ( \<nl> -> \\<nl> ).
cat > $file1 <<EOT
SHELL*:=/bin/sh
SHELLFLAGS*:=-ce

all:
.IF "a" == "a" && \\
   "b" == "b"
	@+echo OK
.ELSE
	@+echo WRONG
.ENDIF
EOT

output=`eval ${DMAKEPROG} -r -f $file1`
result=$?

if test "$output" != "OK"; then
  result=1
fi

test $result -eq 0 && echo "Success - Cleaning up" && $CLEANUP
test $result -ne 0 && echo "Failure!"
exit $result
