#!/bin/sh

# 01.06.2005 Volker Quetschke
# Tests for line continuation in recipes.
# (issue 37053)

: ${DMAKEPROG:=dmake}
file1="mymakefile.mk"
tmpfiles="$file1"
CLEANUP="rm -rf $tmpfiles"

trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15

# Remember to quote variables in generated makefiles( $ -> \$ ).
cat > $file1 <<EOT
# Testing continuation char in recipes
SHELL*:=/bin/sh
SHELLFLAGS*:=-ce

all:
	+@echo line1\
line2

EOT

output=`eval ${DMAKEPROG} -r -f $file1`
result=$?
if test "$output" != "line1line2"; then
  echo "Wrong result"
  result=1
fi


test $result -eq 0 && echo "Success - Cleaning up" && $CLEANUP
test $result -ne 0 && echo "Failure!"
exit $result

