#!/bin/sh

# 03.08.2007 Volker Quetschke
# Check that a %-target without prereq has precedence over one with
# prerequisite.
# (issue 80144)

: ${DMAKEPROG:=dmake}
file1="mfile1.mk"
file2="aaa.aaa"
tmpfiles="$file1 $file2"
CLEANUP="rm -rf $tmpfiles"

trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15

# Create test environment
touch aaa.aaa

# Remember to quote variables in generated makefiles( $ -> \$ ).
cat > $file1 <<EOT
SHELL*:=/bin/sh
SHELLFLAGS*:=-ce

.REMOVE : ; @echo remove \$<

%.a : %.b
	@echo Wrong choice - $@

%.a :
	@echo Right choice

all : xx.a
	@noop all

EOT

output1=`eval ${DMAKEPROG} -rf $file1 2>&1 `
result1=$?

if test "$output1" != "Right choice"; then
  echo "Wrong result: $output1"
  result1=1
else
  echo "OK"
fi

if test $result1 -eq 0 ; then
  echo "Success - Cleaning up"
  $CLEANUP
  exit
else
  echo "Failure!"
  exit 1
fi
