#!/bin/sh

# ensure "-quoting targets (and dependents) works

: ${DMAKEPROG:=dmake}
file1="mfile1.mk"
tmpfiles="$file1"

trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles ; }' 1 2 3 15

# Remove files from prior failed run
rm -rf $tmpfiles

# Remember to quote variables in generated makefiles( $ -> \$ ).
cat > $file1 <<EOT
SHELL*:=/bin/sh
SHELLFLAGS*:=-ce
FILE2 = "a  b"

\$(FILE2) :
	@echo \$@
EOT

output1=`eval ${DMAKEPROG} -r -f $file1 2>&1 `
result1=$?

if [ "$output1" != "a  b" ]; then
  echo "Test 1: Wrong result: $output1"
  result1=1
fi

if test $result1 -eq 0 ; then
  echo "Success - Cleaning up"
  rm -rf $tmpfiles
  result=0
else
  echo "Failure!"
  result=1
fi
exit $result
