#!/bin/sh

# 08.10.2006 Volker Quetschke
# Check that empty dynamic prerequisites are handled correctly.
# (issue 70210)

: ${DMAKEPROG:=dmake}
file1="mfile1.mk"
tmpfiles="$file1"
STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
$CLEANUP # Zap remnants of any failed run
mkdir "$WORKDIR"; cd "$WORKDIR"

trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15

# Remember to quote variables in generated makefiles( $ -> \$ ).
cat > $file1 <<EOT
SHELL*:=/bin/sh
SHELLFLAGS*:=-ce

EMPTYPRQ=

all : \$\$(EMPTYPRQ)
	echo all
EOT

output1=`eval ../${DMAKEPROG} -rf $file1 2>&1 `
result1=$?


if test $result1 -eq 0 ; then
  echo "Success - Cleaning up"
  $CLEANUP
else
  echo "Failure! dmake reported:"
  echo "$output1"
fi
exit $result1
