#!/bin/sh

# 03.08.2007 Volker Quetschke
# Check that ambigous %-target are found.
# prerequisite.
# (issue 80144)

: ${DMAKEPROG:=dmake}
file1="mfile1.mk"
file2="aaa.aaa"
tmpfiles="$file1 $file2"
STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
$CLEANUP # Zap remnants of any failed run
mkdir "$WORKDIR"; cd "$WORKDIR"

trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15

# Create test environment
touch aaa.aaa

# Remember to quote variables in generated makefiles( $ -> \$ ).
cat > $file1 <<EOT
SHELL*:=/bin/sh
SHELLFLAGS*:=-ce

.REMOVE : ; @echo remove \$<

%.a : %.b
	@echo Blah

%.a : xx.b
	@echo Blue

%.b  :
	touch $@

all : xx.a
	@noop all

EOT

output1=`eval ../${DMAKEPROG} -rf $file1 2>&1 `
result1=$?

if echo $output1 | grep ': -- Ambiguous inference chains for target' > /dev/null 2>&1 ; then
  echo "OK"
else
  echo "Test 1: Wrong result: $output1"
  echo
  result1=0
fi

# Errorcode in $result1 means successfull test
if test $result1 -ne 0 ; then
  echo "Success - Cleaning up"
  $CLEANUP
  exit
else
  echo "Failure!"
  exit 1
fi
